name: portfolio_app
description: A personal portfolio app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.3.0
  photo_view: ^0.14.0

flutter:
  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
  uses-material-design: true
